// <auto-generated />
namespace ChemiFriend.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fsbdjkfsdkkhy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fsbdjkfsdkkhy));
        
        string IMigrationMetadata.Id
        {
            get { return "202001250959479_fsbdjkfsdkkhy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
