// <auto-generated />
namespace ChemiFriend.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fsdkfldsyy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fsdkfldsyy));
        
        string IMigrationMetadata.Id
        {
            get { return "202003041756350_fsdkfldsyy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
